// 初期サンプルデータ（受け取った名刺をデジタル化したもの）。
// 日英が表裏セットの名刺は、JA / EN の両フィールドにまとめています。
// このファイルは「サンプルに戻す」操作の元データとしても使われます。
window.MEISHI_SEED = [
  {
    nameJa: "中山 達也", nameEn: "Tatsuya Nakayama",
    companyJa: "西村あさひ法律事務所・外国法共同事業",
    companyEn: "Nishimura & Asahi (Gaikokuho Kyodo Jigyo)",
    titleJa: "パートナー", titleEn: "Partner",
    departmentJa: "", departmentEn: "",
    qualifications: "弁護士・ニューヨーク州弁護士 / Attorney-at-Law, Admitted in Japan & New York",
    email: "ta.nakayama@nishimura.com",
    phone: "03-6250-6347", phoneSub: "03-6250-6200（代表）", fax: "03-6250-7200", mobile: "",
    postalCode: "100-8124",
    addressJa: "東京都千代田区大手町1-1-2 大手門タワー",
    addressEn: "Otemon Tower, 1-1-2 Otemachi, Chiyoda-ku, Tokyo 100-8124, Japan",
    website: "https://www.nishimura.com/",
    tags: ["法律", "弁護士"], notes: "", favorite: false
  },
  {
    nameJa: "小林 咲花", nameEn: "Sakka Kobayashi",
    companyJa: "西村あさひ法律事務所・外国法共同事業",
    companyEn: "Nishimura & Asahi (Gaikokuho Kyodo Jigyo)",
    titleJa: "パートナー", titleEn: "Partner",
    departmentJa: "", departmentEn: "",
    qualifications: "弁護士（日本、ニューヨーク州及びテキサス州） / Attorney-at-Law, Admitted in Japan, New York & Texas",
    email: "s.kobayashi@nishimura.com",
    phone: "03-6250-6605", phoneSub: "03-6250-6200（代表）", fax: "03-6250-7200", mobile: "",
    postalCode: "100-8124",
    addressJa: "東京都千代田区大手町1-1-2 大手門タワー",
    addressEn: "Otemon Tower, 1-1-2 Otemachi, Chiyoda-ku, Tokyo 100-8124, Japan",
    website: "https://www.nishimura.com/",
    tags: ["法律", "弁護士"], notes: "", favorite: false
  },
  {
    nameJa: "榊 遥佳", nameEn: "Haruka Sakaki",
    companyJa: "西村あさひ法律事務所・外国法共同事業",
    companyEn: "Nishimura & Asahi (Gaikokuho Kyodo Jigyo)",
    titleJa: "弁護士", titleEn: "Attorney-at-Law",
    departmentJa: "", departmentEn: "",
    qualifications: "",
    email: "h.sakaki@nishimura.com",
    phone: "03-6250-7561（直通）", phoneSub: "", fax: "", mobile: "",
    postalCode: "100-8124",
    addressJa: "東京都千代田区大手町1-1-2 大手門タワー",
    addressEn: "Otemon Tower, 1-1-2 Otemachi, Chiyoda-ku, Tokyo 100-8124, Japan",
    website: "https://www.nishimura.com/",
    tags: ["法律", "弁護士"], notes: "", favorite: false
  },
  {
    nameJa: "佐々木 享子", nameEn: "Kyoko Sasaki",
    companyJa: "住友生命保険相互会社",
    companyEn: "Sumitomo Life Insurance Company",
    titleJa: "エグゼクティブコンサルタント", titleEn: "",
    departmentJa: "東京本社すみれい事業部 FP営業課", departmentEn: "",
    qualifications: "2級ファイナンシャル・プランニング技能士 / 2025年度MDRT成績資格終身会員 / Court of the Table 会員",
    email: "sasaki-kyouko@sumisei.jp",
    phone: "03-3588-0601", phoneSub: "03-3588-0602", fax: "03-3588-0726", mobile: "",
    postalCode: "",
    addressJa: "東京都港区赤坂3-3-3 住友生命赤坂ビル3F",
    addressEn: "",
    website: "",
    tags: ["保険", "FP"], notes: "日本語名刺のみ受領。", favorite: false
  },
  {
    nameJa: "植木 浩", nameEn: "Ueki Hiroshi",
    companyJa: "T&Dフィナンシャル生命保険株式会社",
    companyEn: "T&D Financial Life Insurance Company",
    titleJa: "リスク管理部長", titleEn: "Senior Manager",
    departmentJa: "保険計理人", departmentEn: "Risk Management Division",
    qualifications: "FIAJ / 日本アクチュアリー会正会員 / 公認内部監査人（CIA） / 公認情報システム監査人（CISA）",
    email: "ueki.hiroshi@tdf-life.co.jp",
    phone: "050-1730-9403", phoneSub: "", fax: "", mobile: "",
    postalCode: "105-0023",
    addressJa: "東京都港区芝浦1-1-1",
    addressEn: "1-1-1, Shibaura, Minato-ku, Tokyo, 105-0023, Japan",
    website: "https://www.tdf-life.co.jp/",
    tags: ["保険", "T&D"], notes: "", favorite: false
  },
  {
    nameJa: "杉本 和大", nameEn: "Sugimoto Kazuhiro",
    companyJa: "T&Dフィナンシャル生命保険株式会社",
    companyEn: "T&D Financial Life Insurance Company",
    titleJa: "経営管理部長", titleEn: "General Manager",
    departmentJa: "", departmentEn: "Finance & Accounting Department",
    qualifications: "F.I.A.J. / 日本アクチュアリー会正会員",
    email: "sugimoto.kazuhiro@tdf-life.co.jp",
    phone: "03-6745-6812", phoneSub: "", fax: "", mobile: "050-1730-9414（直通）",
    postalCode: "105-0023",
    addressJa: "東京都港区芝浦1-1-1",
    addressEn: "1-1-1, Shibaura, Minato-ku, Tokyo 105-0023, Japan",
    website: "https://www.tdf-life.co.jp/",
    tags: ["保険", "T&D"], notes: "", favorite: false
  },
  {
    nameJa: "貴田 岳史", nameEn: "Takeshi Kida",
    companyJa: "T&Dフィナンシャル生命保険株式会社",
    companyEn: "T&D Financial Life Insurance Company",
    titleJa: "企画部長", titleEn: "",
    departmentJa: "", departmentEn: "",
    qualifications: "",
    email: "kida.takeshi.30@tdf-life.co.jp",
    phone: "03-6745-6808", phoneSub: "", fax: "", mobile: "",
    postalCode: "105-0023",
    addressJa: "東京都港区芝浦1丁目1番1号",
    addressEn: "",
    website: "https://www.tdf-life.co.jp/",
    tags: ["保険", "T&D"], notes: "日本語名刺のみ受領。", favorite: false
  },
  {
    nameJa: "木下 正治", nameEn: "Masaharu Kinoshita",
    companyJa: "T&Dユナイテッドキャピタル株式会社",
    companyEn: "T&D United Capital Co., Ltd",
    titleJa: "取締役執行役員 事業開発部長", titleEn: "Board Director and Executive Officer",
    departmentJa: "", departmentEn: "Managing Director and Head of Business Development",
    qualifications: "CMA",
    email: "masaharu.kinoshita@tduc.co.jp",
    phone: "03-3272-6864", phoneSub: "masaharu.kinoshita@td-holdings.co.jp（メール）", fax: "", mobile: "050-3628-7117",
    postalCode: "103-6031",
    addressJa: "東京都中央区日本橋2丁目7番1号",
    addressEn: "7-1, Nohonbashi 2-chome, Chuo-ku, Tokyo 103-6031, Japan",
    website: "",
    tags: ["金融", "T&D"], notes: "", favorite: false
  },
  {
    nameJa: "松本 匡史", nameEn: "Tadashi Matsumoto",
    companyJa: "農林中央金庫",
    companyEn: "The Norinchukin Bank",
    titleJa: "資金為替部 副部長 企画グループ長", titleEn: "Global Co-Head of Treasury & Forex Division",
    departmentJa: "資金為替部", departmentEn: "Treasury & Forex Division",
    qualifications: "",
    email: "tadashi_matsumoto@nochubank.or.jp",
    phone: "050-3123-5551", phoneSub: "", fax: "", mobile: "",
    postalCode: "100-8155",
    addressJa: "東京都千代田区大手町1-2-1 Otemachi One タワー",
    addressEn: "1-2-1, Otemachi, Chiyoda-ku, Tokyo, 100-8155, Japan",
    website: "https://www.nochubank.or.jp/",
    tags: ["金融", "農林中金"], notes: "", favorite: false
  },
  {
    nameJa: "間島 奈美", nameEn: "Nami Majima",
    companyJa: "農林中央金庫",
    companyEn: "The Norinchukin Bank",
    titleJa: "資金為替部 資金為替班 部長代理", titleEn: "Senior Manager, Money Markets & Forex",
    departmentJa: "グローバル・インベストメンツ本部", departmentEn: "Treasury & Forex Division, Global Investments",
    qualifications: "",
    email: "n-majima@nochubank.or.jp",
    phone: "03-6362-7106", phoneSub: "", fax: "", mobile: "",
    postalCode: "100-8155",
    addressJa: "東京都千代田区大手町一丁目2番1号 Otemachi One タワー",
    addressEn: "2-1, Otemachi 1-chome, Chiyoda-ku, Tokyo 100-8155, Japan",
    website: "https://www.nochubank.or.jp/",
    tags: ["金融", "農林中金"], notes: "", favorite: false
  },
  {
    nameJa: "橋本 哲也", nameEn: "Tetsuya Hashimoto",
    companyJa: "農林中央金庫",
    companyEn: "The Norinchukin Bank",
    titleJa: "財務企画部 部長", titleEn: "General Manager",
    departmentJa: "財務企画部", departmentEn: "Financial Planning and Control Division",
    qualifications: "",
    email: "t-hashimoto@nochubank.or.jp",
    phone: "050-3123-5622", phoneSub: "", fax: "", mobile: "",
    postalCode: "100-8155",
    addressJa: "東京都千代田区大手町1-2-1 Otemachi One タワー",
    addressEn: "1-2-1, Otemachi, Chiyoda-ku, Tokyo, 100-8155, Japan",
    website: "https://www.nochubank.or.jp/",
    tags: ["金融", "農林中金"], notes: "", favorite: false
  },
  {
    nameJa: "鶴賀 重樹", nameEn: "Shigeki Tsuruga",
    companyJa: "農林中央金庫",
    companyEn: "The Norinchukin Bank",
    titleJa: "資金為替部 副部長 企画グループ長", titleEn: "Global Head of Treasury & Forex Division",
    departmentJa: "資金為替部", departmentEn: "Treasury & Forex Division",
    qualifications: "",
    email: "stsuruga@nochubank.or.jp",
    phone: "050-3853-0271", phoneSub: "", fax: "", mobile: "",
    postalCode: "100-8155",
    addressJa: "東京都千代田区大手町一丁目2番1号 Otemachi One タワー",
    addressEn: "2-1, Otemachi 1-chome, Chiyoda-ku, Tokyo 100-8155, Japan",
    website: "https://www.nochubank.or.jp/",
    tags: ["金融", "農林中金"], notes: "", favorite: false
  },
  {
    nameJa: "阿久津 怜生", nameEn: "Reo Akutsu",
    companyJa: "JPモルガン証券株式会社",
    companyEn: "JPMorgan Securities Japan Co., Ltd.",
    titleJa: "金融法人グループ", titleEn: "Financial Institutions Group",
    departmentJa: "投資銀行本部 投資銀行部", departmentEn: "Investment Banking, Investment Banking Division",
    qualifications: "",
    email: "reo.akutsu@jpmorgan.com",
    phone: "03-6736-1204", phoneSub: "", fax: "", mobile: "",
    postalCode: "100-6432",
    addressJa: "東京都千代田区丸の内2丁目7番3号 東京ビルディング",
    addressEn: "Tokyo Building, 7-3, Marunouchi 2-chome, Chiyoda-ku, Tokyo 100-6432",
    website: "https://www.jpmorgan.com/",
    tags: ["金融", "投資銀行"], notes: "", favorite: false
  },
  {
    nameJa: "平賀 義啓", nameEn: "Yoshihiro Hiraga",
    companyJa: "日本郵政株式会社",
    companyEn: "Japan Post Holdings Co., Ltd.",
    titleJa: "経営企画部 次長", titleEn: "",
    departmentJa: "経営企画部", departmentEn: "",
    qualifications: "",
    email: "yoshihiro.hiraga.xr@jp-holdings.jp",
    phone: "03-3477-0213", phoneSub: "03-3477-0222（直通・内線312855）", fax: "", mobile: "",
    postalCode: "100-8791",
    addressJa: "東京都千代田区大手町二丁目3番1号",
    addressEn: "",
    website: "https://www.japanpost.jp/",
    tags: ["官公庁系", "郵政"], notes: "日本語名刺のみ受領。", favorite: false
  }
];
